SET DATABASE SQL SYNTAX MSS TRUE



CREATE VIEW dbo.vw_REFERENCE_DATA AS SELECT SUBJECT_ID, GAI_ADOPTION_DT, IN_SERVICE_DT,	OUT_OF_SERVICE_DT, LIST_NM, CONTEXT_NM,	ITEM_CD, SHORT_DESC, LONG_DESC, NOTES_TXT FROM dbo.reference_DATA;

	